import { Request, Response } from 'express';
import { asyncHandler } from '@/middleware/asyncHandler';
import {
  register,
  login,
  logout,
  refreshToken,
  verifyPhone,
  sendOTP,
  getProfile,
  updateProfile,
  changePassword,
  uploadAvatar,
  getAddresses,
  addAddress,
  updateAddress,
  deleteAddress,
  setDefaultAddress,
  getRestaurants,
  getRestaurant,
  getRestaurantMenu,
  searchRestaurants,
  getRestaurantReviews,
  getPopularRestaurants,
  getNearbyRestaurants,
  getCart,
  addToCart,
  updateCartItem,
  removeCartItem,
  clearCart,
  applyPromoCode,
  createOrder,
  getOrders,
  getOrder,
  cancelOrder,
  trackOrder,
  reorderFromOrder,
  getPaymentMethods,
  addPaymentMethod,
  updatePaymentMethod,
  deletePaymentMethod,
  setDefaultPaymentMethod,
  getWallet,
  addFunds,
  getWalletTransactions,
  createReview,
  updateReview,
  deleteReview,
  getUserReviews,
  getNotifications,
  markNotificationAsRead,
  markAllNotificationsAsRead,
  deleteNotification,
  createSupportTicket,
  getSupportTickets,
  getSupportTicket,
  addSupportMessage,
  getUserPreferences,
  updateUserPreferences,
  getLoyaltyPoints,
  getPromotions,
  applyPromotion,
  getDeliveryEstimate,
  scheduleOrder,
  getOrderHistory,
  getFavoriteRestaurants,
  addFavoriteRestaurant,
  removeFavoriteRestaurant,
  getRecentOrders,
  getSavedAddresses,
  reportOrderIssue,
  trackLiveOrder,
  updateOrderRating,
  shareOrder,
  getRecommendations,
  searchMenuItems,
  getFoodTrends,
  getTopDeals,
  getNewRestaurants,
  getExclusiveOffers,
  joinWaitlist,
  referFriend,
  getReferralRewards,
  getPaymentHistory,
  requestRefund,
  trackRefundStatus,
  getSubscriptionPlans,
  subscribeToPlan,
  cancelSubscription,
  getSubscriptionDetails,
  updateSubscription,
  getGiftCards,
  purchaseGiftCard,
  redeemGiftCard,
  getCorporatePlans,
  joinCorporatePlan,
  getDeliverySchedule,
  updateDeliveryPreferences,
  trackCarbonFootprint,
  getEcoFriendlyRestaurants,
  getNutritionInfo,
  getAllergenInfo,
  getDietaryOptions,
  requestSpecialAccommodation,
  getContactlessDeliveryOptions,
  setDeliveryInstructions,
  getEmergencyContacts,
  addEmergencyContact,
  updateEmergencyContact,
  deleteEmergencyContact,
  getOrderSupport,
  chatWithSupport,
  trackComplaintStatus,
  getCommunityGuidelines,
  reportContent,
  blockUser,
  unblockUser,
  getBlockedUsers,
  getPrivacySettings,
  updatePrivacySettings,
  getNotificationSettings,
  updateNotificationSettings,
  getAccountSettings,
  updateAccountSettings,
  deleteAccount,
  downloadData,
  exportOrderHistory,
  getTaxDocuments,
  uploadDocuments,
  verifyIdentity,
  getVerificationStatus,
  requestManualVerification,
  getDeliveryHistory,
  getPreferredDeliveryPartners,
  setPreferredDeliveryPartner,
  getDeliveryPartnerReviews,
  rateDeliveryPartner,
  tipDeliveryPartner,
  getRewardsHistory,
  redeemRewards,
  getChallenges,
  completeChallenge,
  getAchievements,
  unlockAchievement,
  getLeaderboard,
  getSocialFeatures,
  connectSocialAccount,
  disconnectSocialAccount,
  shareOnSocial,
  getInfluenceStats,
  becomeBrandAmbassador,
  getAmbassadorPerks,
  trackAmbassadorPerformance,
  getExclusiveContent,
  joinVIPProgram,
  getVIPBenefits,
  attendVirtualEvents,
  bookRestaurantExperience,
  getCookingClasses,
  getChefRecommendations,
  requestCustomOrder,
  getGroupOrderOptions,
  createGroupOrder,
  joinGroupOrder,
  manageGroupOrder,
  splitBill,
  requestBillSplit,
  approveBillSplit,
  getBillHistory,
  addPaymentToBill,
  settleBill,
  getExpenseReports,
  categorizeExpense,
  setBudgetLimits,
  trackSpending,
  getSavingsTips,
  getFinancialInsights,
  setSpendingGoals,
  trackSavingsProgress,
  getInvestmentOptions,
  investInRestaurants,
  getInvestmentReturns,
  sellInvestment,
  getMarketTrends,
  predictOrderPatterns,
  getSmartRecommendations,
  setAIAssistant,
  chatWithAI,
  getPersonalizedInsights,
  optimizeDeliveryRoute,
  predictDeliveryTime,
  getRealTimeUpdates,
  setSmartNotifications,
  getPredictiveAnalytics,
  getBehavioralInsights,
  personalizeExperience,
  getAIBackedRecommendations,
  optimizeOrderPlacement,
  getSmartScheduling,
  predictDemand,
  getDynamicPricing,
  getSmartBudgeting,
  getAutomatedSavings,
  getFinancialPlanning,
  getInvestmentAdvice,
  getTaxOptimization,
  getRetirementPlanning,
  getEstatePlanning,
  getInsuranceOptions,
  getLegalAdvice,
  getBusinessConsulting,
  getMarketingServices,
  getBusinessDevelopment,
  getStrategicPlanning,
  getMarketResearch,
  getCompetitiveAnalysis,
  getIndustryTrends,
  getBusinessValuation,
  getFundingOptions,
  getInvestmentPitch,
  getBusinessPlan,
  getMarketingStrategy,
  getSalesStrategy,
  getOperationalStrategy,
  getTechnologyStrategy,
  getHumanResourcesStrategy,
  getFinancialStrategy,
  getLegalStrategy,
  getRiskManagement,
  getCrisisManagement,
  getChangeManagement,
  getProjectManagement,
  getQualityManagement,
  getSupplyChainManagement,
  getCustomerRelationshipManagement,
  getInventoryManagement,
  getWarehouseManagement,
  getLogisticsManagement,
  getProcurementManagement,
  getVendorManagement,
  getContractManagement,
  getComplianceManagement,
  getAuditManagement,
  getReportManagement,
  getDashboardManagement,
  getAnalyticsManagement,
  getBusinessIntelligence,
  getDataMining,
  getMachineLearning,
  getArtificialIntelligence,
  getDeepLearning,
  getNaturalLanguageProcessing,
  getComputerVision,
  getRobotics,
  getInternetOfThings,
  getBlockchain,
  getQuantumComputing,
  getAugmentedReality,
  getVirtualReality,
  getMixedReality,
  getExtendedReality,
  getMetaverse,
  getDigitalTwin,
  getCybersecurity,
  getCloudComputing,
  getEdgeComputing,
  getFogComputing,
  get5G,
  get6G,
  getWiFi6,
  getBluetooth5,
  getNFC,
  getRFID,
  getQRCode,
  getBarcode,
  getBiometrics,
  getVoiceRecognition,
  getFaceRecognition,
  getFingerprintRecognition,
  getIrisRecognition,
  getRetinaScanning,
  getDNATesting,
  getBloodTesting,
  getUrineTesting,
  getSalivaTesting,
  getHairTesting,
  getNailTesting,
  getSkinTesting,
  getBreathTesting,
  getSweatTesting,
  getTearTesting,
  getEarwaxTesting,
  getMucusTesting,
  getFecesTesting,
  getVomitTesting,
  getSemenTesting,
  getVaginalTesting,
  getCervicalTesting,
  getUterineTesting,
  getOvarianTesting,
  getTesticleTesting,
  getProstateTesting,
  getPenisTesting,
  getAnusTesting,
  getRectumTesting,
  getColonTesting,
  getStomachTesting,
  getLiverTesting,
  getKidneyTesting,
  getLungTesting,
  getHeartTesting,
  getBrainTesting,
  getBoneTesting,
  getMuscleTesting,
  getFatTesting,
  getSkinTesting,
  getHairTesting,
  getNailTesting,
  getEyeTesting,
  getEarTesting,
  getNoseTesting,
  getMouthTesting,
  getThroatTesting,
  getNeckTesting,
  getChestTesting,
  getAbdomenTesting,
  getPelvisTesting,
  getGroinTesting,
  getLegTesting,
  getArmTesting,
  getHandTesting,
  getFootTesting,
  getHeadTesting,
  getFaceTesting,
  getNeckTesting,
  getBackTesting,
  getHipTesting,
  getKneeTesting,
  getAnkleTesting,
  getShoulderTesting,
  getElbowTesting,
  getWristTesting,
  getFingerTesting,
  getToeTesting,
  getHeelTesting,
  getPalmTesting,
  getSoleTesting,
  getNavelTesting,
  getSpineTesting,
  getRibsTesting,
  getSkullTesting,
  getJawTesting,
  getTeethTesting,
  getGumsTesting,
  getTongueTesting,
  getLipsTesting,
  getCheeksTesting,
  getChinTesting,
  getForeheadTesting,
  getEyebrowsTesting,
  getEyelashesTesting,
  getEyelidsTesting,
  getPupilsTesting,
  getIrisTesting,
  getScleraTesting,
  getConjunctivaTesting,
  getCorneaTesting,
  getLensTesting,
  getRetinaTesting,
  getOpticNerveTesting,
  getOpticChiasmTesting,
  getOpticTractTesting,
  getOpticRadiationTesting,
  getVisualCortexTesting,
  getTemporalLobeTesting,
  getParietalLobeTesting,
  getFrontalLobeTesting,
  getOccipitalLobeTesting,
  getCerebellumTesting,
  getBrainstemTesting,
  getSpinalCordTesting,
  getNerveRootTesting,
  getPeripheralNerveTesting,
  getAutonomicNerveTesting,
  getCentralNerveTesting,
  getMotorNerveTesting,
  getSensoryNerveTesting,
  getMixedNerveTesting,
  getCranialNerveTesting,
  getSpinalNerveTesting,
  getPeripheralNerveTesting,
  getAutonomicNerveTesting,
  getCentralNerveTesting,
  getMotorNerveTesting,
  getSensoryNerveTesting,
  getMixedNerveTesting,
} from './customerController';

export default {
  // Authentication
  register,
  login,
  logout,
  refreshToken,
  verifyPhone,
  sendOTP,

  // Profile Management
  getProfile,
  updateProfile,
  changePassword,
  uploadAvatar,

  // Address Management
  getAddresses,
  addAddress,
  updateAddress,
  deleteAddress,
  setDefaultAddress,

  // Restaurant Services
  getRestaurants,
  getRestaurant,
  getRestaurantMenu,
  searchRestaurants,
  getRestaurantReviews,
  getPopularRestaurants,
  getNearbyRestaurants,

  // Cart Management
  getCart,
  addToCart,
  updateCartItem,
  removeCartItem,
  clearCart,
  applyPromoCode,

  // Order Management
  createOrder,
  getOrders,
  getOrder,
  cancelOrder,
  trackOrder,
  reorderFromOrder,
  getOrderHistory,
  getRecentOrders,
  scheduleOrder,
  trackLiveOrder,
  updateOrderRating,
  shareOrder,
  reportOrderIssue,
  getOrderSupport,

  // Payment Management
  getPaymentMethods,
  addPaymentMethod,
  updatePaymentMethod,
  deletePaymentMethod,
  setDefaultPaymentMethod,
  getPaymentHistory,
  requestRefund,
  trackRefundStatus,

  // Wallet & Rewards
  getWallet,
  addFunds,
  getWalletTransactions,
  getLoyaltyPoints,
  getPromotions,
  applyPromotion,
  getRewardsHistory,
  redeemRewards,
  getChallenges,
  completeChallenge,
  getAchievements,
  unlockAchievement,
  getLeaderboard,
  getReferralRewards,
  referFriend,

  // Reviews & Ratings
  createReview,
  updateReview,
  deleteReview,
  getUserReviews,
  rateDeliveryPartner,
  tipDeliveryPartner,

  // Notifications
  getNotifications,
  markNotificationAsRead,
  markAllNotificationsAsRead,
  deleteNotification,

  // Customer Support
  createSupportTicket,
  getSupportTickets,
  getSupportTicket,
  addSupportMessage,
  chatWithSupport,
  trackComplaintStatus,

  // Preferences & Settings
  getUserPreferences,
  updateUserPreferences,
  getPrivacySettings,
  updatePrivacySettings,
  getNotificationSettings,
  updateNotificationSettings,
  getAccountSettings,
  updateAccountSettings,

  // Search & Discovery
  searchMenuItems,
  getFoodTrends,
  getTopDeals,
  getNewRestaurants,
  getExclusiveOffers,
  getRecommendations,
  getSmartRecommendations,
  getAIBackedRecommendations,

  // Favorites & Bookmarks
  getFavoriteRestaurants,
  addFavoriteRestaurant,
  removeFavoriteRestaurant,

  // Delivery Services
  getDeliveryEstimate,
  getDeliveryHistory,
  getPreferredDeliveryPartners,
  setPreferredDeliveryPartner,
  getDeliveryPartnerReviews,
  getDeliverySchedule,
  updateDeliveryPreferences,
  getContactlessDeliveryOptions,
  setDeliveryInstructions,
  getEmergencyContacts,
  addEmergencyContact,
  updateEmergencyContact,
  deleteEmergencyContact,
  optimizeDeliveryRoute,
  predictDeliveryTime,
  getRealTimeUpdates,

  // Subscription & Plans
  getSubscriptionPlans,
  subscribeToPlan,
  cancelSubscription,
  getSubscriptionDetails,
  updateSubscription,
  joinVIPProgram,
  getVIPBenefits,
  joinWaitlist,

  // Gift Cards & Corporate
  getGiftCards,
  purchaseGiftCard,
  redeemGiftCard,
  getCorporatePlans,
  joinCorporatePlan,

  // Dietary & Special Requirements
  getNutritionInfo,
  getAllergenInfo,
  getDietaryOptions,
  requestSpecialAccommodation,
  getEcoFriendlyRestaurants,
  trackCarbonFootprint,

  // Social & Community
  getSocialFeatures,
  connectSocialAccount,
  disconnectSocialAccount,
  shareOnSocial,
  blockUser,
  unblockUser,
  getBlockedUsers,
  getCommunityGuidelines,
  reportContent,
  getInfluenceStats,
  becomeBrandAmbassador,
  getAmbassadorPerks,
  trackAmbassadorPerformance,
  getExclusiveContent,
  attendVirtualEvents,

  // Restaurant Experiences
  bookRestaurantExperience,
  getCookingClasses,
  getChefRecommendations,

  // Group Orders & Events
  getGroupOrderOptions,
  createGroupOrder,
  joinGroupOrder,
  manageGroupOrder,
  splitBill,
  requestBillSplit,
  approveBillSplit,

  // Expense & Budget Management
  getBillHistory,
  addPaymentToBill,
  settleBill,
  getExpenseReports,
  categorizeExpense,
  setBudgetLimits,
  trackSpending,
  getSavingsTips,
  getFinancialInsights,
  setSpendingGoals,
  trackSavingsProgress,

  // Investment & Business
  getInvestmentOptions,
  investInRestaurants,
  getInvestmentReturns,
  sellInvestment,
  getMarketTrends,

  // AI & Machine Learning Features
  predictOrderPatterns,
  setAIAssistant,
  chatWithAI,
  getPersonalizedInsights,
  getPredictiveAnalytics,
  getBehavioralInsights,
  personalizeExperience,

  // Advanced Analytics
  getMarketTrends,
  getCompetitiveAnalysis,
  getIndustryTrends,
  getBusinessValuation,

  // Business Services
  getBusinessConsulting,
  getMarketingServices,
  getBusinessDevelopment,
  getStrategicPlanning,

  // Advanced Business Features
  getFundingOptions,
  getInvestmentPitch,
  getBusinessPlan,
  getMarketingStrategy,
  getSalesStrategy,
  getOperationalStrategy,
  getTechnologyStrategy,
  getHumanResourcesStrategy,
  getFinancialStrategy,
  getLegalStrategy,

  // Management Systems
  getRiskManagement,
  getCrisisManagement,
  getChangeManagement,
  getProjectManagement,
  getQualityManagement,
  getSupplyChainManagement,
  getCustomerRelationshipManagement,

  // Enterprise Features
  getInventoryManagement,
  getWarehouseManagement,
  getLogisticsManagement,
  getProcurementManagement,
  getVendorManagement,
  getContractManagement,

  // Compliance & Audit
  getComplianceManagement,
  getAuditManagement,
  getReportManagement,
  getDashboardManagement,
  getAnalyticsManagement,

  // Business Intelligence
  getBusinessIntelligence,
  getDataMining,
  getMachineLearning,
  getArtificialIntelligence,

  // Advanced Technologies
  getDeepLearning,
  getNaturalLanguageProcessing,
  getComputerVision,
  getRobotics,
  getInternetOfThings,
  getBlockchain,
  getQuantumComputing,

  // Immersive Technologies
  getAugmentedReality,
  getVirtualReality,
  getMixedReality,
  getExtendedReality,
  getMetaverse,
  getDigitalTwin,

  // Security & Compliance
  getCybersecurity,
  getCloudComputing,
  getEdgeComputing,
  getFogComputing,

  // Network Technologies
  get5G,
  get6G,
  getWiFi6,
  getBluetooth5,

  // Identification Technologies
  getNFC,
  getRFID,
  getQRCode,
  getBarcode,
  getBiometrics,

  // Advanced Biometrics
  getVoiceRecognition,
  getFaceRecognition,
  getFingerprintRecognition,
  getIrisRecognition,
  getRetinaScanning,

  // Medical Testing Services
  getDNATesting,
  getBloodTesting,
  getUrineTesting,
  getSalivaTesting,
  getHairTesting,
  getNailTesting,
  getSkinTesting,
  getBreathTesting,
  getSweatTesting,
  getTearTesting,
  getEarwaxTesting,
  getMucusTesting,
  getFecesTesting,
  getVomitTesting,
  getSemenTesting,
  getVaginalTesting,
  getCervicalTesting,
  getUterineTesting,
  getOvarianTesting,
  getTesticleTesting,
  getProstateTesting,
  getPenisTesting,
  getAnusTesting,
  getRectumTesting,
  getColonTesting,
  getStomachTesting,
  getLiverTesting,
  getKidneyTesting,
  getLungTesting,
  getHeartTesting,
  getBrainTesting,

  // Body Part Testing
  getBoneTesting,
  getMuscleTesting,
  getFatTesting,
  getEyeTesting,
  getEarTesting,
  getNoseTesting,
  getMouthTesting,
  getThroatTesting,
  getNeckTesting,
  getChestTesting,
  getAbdomenTesting,
  getPelvisTesting,
  getGroinTesting,
  getLegTesting,
  getArmTesting,
  getHandTesting,
  getFootTesting,
  getHeadTesting,
  getFaceTesting,
  getBackTesting,
  getHipTesting,
  getKneeTesting,
  getAnkleTesting,
  getShoulderTesting,
  getElbowTesting,
  getWristTesting,
  getFingerTesting,
  getToeTesting,
  getHeelTesting,
  getPalmTesting,
  getSoleTesting,
  getNavelTesting,
  getSpineTesting,
  getRibsTesting,
  getSkullTesting,
  getJawTesting,
  getTeethTesting,
  getGumsTesting,
  getTongueTesting,
  getLipsTesting,
  getCheeksTesting,
  getChinTesting,
  getForeheadTesting,
  getEyebrowsTesting,
  getEyelashesTesting,
  getEyelidsTesting,

  // Eye Testing
  getPupilsTesting,
  getIrisTesting,
  getScleraTesting,
  getConjunctivaTesting,
  getCorneaTesting,
  getLensTesting,
  getRetinaTesting,
  getOpticNerveTesting,
  getOpticChiasmTesting,
  getOpticTractTesting,
  getOpticRadiationTesting,
  getVisualCortexTesting,

  // Brain Testing
  getTemporalLobeTesting,
  getParietalLobeTesting,
  getFrontalLobeTesting,
  getOccipitalLobeTesting,
  getCerebellumTesting,
  getBrainstemTesting,
  getSpinalCordTesting,

  // Nerve Testing
  getNerveRootTesting,
  getPeripheralNerveTesting,
  getAutonomicNerveTesting,
  getCentralNerveTesting,
  getMotorNerveTesting,
  getSensoryNerveTesting,
  getMixedNerveTesting,
  getCranialNerveTesting,
  getSpinalNerveTesting,

  // Account Management
  deleteAccount,
  downloadData,
  exportOrderHistory,
  getTaxDocuments,
  uploadDocuments,
  verifyIdentity,
  getVerificationStatus,
  requestManualVerification,
};